# Generated by Django 2.2.10 on 2020-02-26 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onepanman_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemRuleInfo',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.ForeignKey(db_column='PROBLEM', on_delete=django.db.models.deletion.PROTECT, to='onepanman_api.Problem', verbose_name='문제')),
                ('rule', models.ForeignKey(db_column='RULE', on_delete=django.db.models.deletion.PROTECT, to='onepanman_api.RuleInfo', verbose_name='규칙')),
            ],
            options={
                'verbose_name': '문제 별 규칙정보',
                'verbose_name_plural': '문제 별 규칙정보',
                'db_table': 'PROBLEMRULEINFO',
                'ordering': ['id'],
            },
        ),
    ]
