# Generated by Django 2.2.10 on 2020-02-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onepanman_api', '0002_problemruleinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruleinfo',
            name='type',
            field=models.CharField(choices=[('placement', '착수'), ('action', '액션'), ('ending', '엔딩')], db_column='TYPE', max_length=30, verbose_name='규칙종류'),
        ),
    ]
