# Generated by Django 2.2.10 on 2020-02-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onepanman_api', '0003_auto_20200226_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformationinproblem',
            name='tier',
            field=models.CharField(choices=[('Bronze', 'Bronze'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Platinum', 'Platinum'), ('Diamond', 'Diamond'), ('Challenger', 'Challenger')], db_column='TIRE', default='Bronze', max_length=20, verbose_name='등급'),
        ),
    ]
