# Generated by Django 2.2.10 on 2020-03-01 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onepanman_api', '0004_auto_20200226_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.CharField(db_column='WINNER', default='None', max_length=50, verbose_name='승리자'),
        ),
    ]
