# Generated by Django 2.2.10 on 2020-03-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onepanman_api', '0006_auto_20200303_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='board_info',
            field=models.TextField(db_column='BOARD_INFO', default='0', verbose_name='시작 보드 정보'),
        ),
    ]
