# Generated by Django 2.2.10 on 2020-03-04 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onepanman_api', '0007_auto_20200303_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='tier',
            field=models.CharField(db_column='TIER', default='Bronze', max_length=50, verbose_name='등급'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='tier_score',
            field=models.IntegerField(db_column='TIER_SCORE', default=0, verbose_name='등급 점수'),
        ),
    ]
