# Generated by Django 2.2.10 on 2020-03-08 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onepanman_api', '0008_auto_20200304_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='rule',
            field=models.TextField(db_column='RULE', default='empty', verbose_name='문제 규칙'),
        ),
    ]
