# Generated by Django 2.2.10 on 2020-03-17 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onepanman_api', '0010_auto_20200315_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='turn',
        ),
        migrations.AddField(
            model_name='game',
            name='challenger_score',
            field=models.IntegerField(db_column='CHALLENGER_SCORE', default=500, verbose_name='challenger_score'),
        ),
        migrations.AddField(
            model_name='game',
            name='opposite_score',
            field=models.IntegerField(db_column='OPPOSITE_SCORE', default=500, verbose_name='opposite_score'),
        ),
        migrations.AlterField(
            model_name='game',
            name='result',
            field=models.CharField(choices=[('playing', 'playing'), ('finish', 'finish'), ('challenger_error', 'challenger_error'), ('opposite_error', 'opposite_error')], db_column='RESULT', default='playing', max_length=50, verbose_name='결과'),
        ),
        migrations.AlterField(
            model_name='userinformationinproblem',
            name='score',
            field=models.IntegerField(db_column='SCORE', default=500, verbose_name='점수'),
        ),
    ]
