# Generated by Django 2.2.10 on 2020-03-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onepanman_api', '0011_auto_20200317_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='language',
            field=models.CharField(choices=[('C', 'C'), ('C++', 'C++'), ('PYTHON', 'PYTHON'), ('JAVA', 'JAVA')], db_column='LANGUAGE', max_length=50, verbose_name='언어'),
        ),
    ]
