# Generated by Django 2.2.10 on 2020-03-19 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onepanman_api', '0013_auto_20200319_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='rule',
            field=models.TextField(db_column='RULE', default='{"obj_num": ,"placement" : , "action" : , "ending": ,}', verbose_name='문제 규칙'),
        ),
        migrations.DeleteModel(
            name='ProblemRuleInfo',
        ),
        migrations.DeleteModel(
            name='RuleInfo',
        ),
    ]
