# Generated by Django 2.2.10 on 2020-03-20 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onepanman_api', '0014_auto_20200319_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='placement_record',
            field=models.TextField(db_column='PLACEMENT_RECORD', default='[]', verbose_name='착수기록'),
        ),
        migrations.AlterField(
            model_name='game',
            name='record',
            field=models.TextField(db_column='RECORD', default='[]', verbose_name='게임기록'),
        ),
    ]
