# Generated by Django 2.2.10 on 2020-04-01 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onepanman_api', '0015_auto_20200320_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupinfo',
            name='ranking',
            field=models.IntegerField(db_column='RANKING', null=True, unique=True, verbose_name='랭킹'),
        ),
    ]
