# Generated by Django 2.2.10 on 2020-04-01 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onepanman_api', '0016_auto_20200401_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupinfo',
            name='score',
            field=models.IntegerField(db_column='SCORE', default=0, verbose_name='점수'),
        ),
    ]
