# Generated by Django 2.2.10 on 2020-04-01 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onepanman_api', '0017_groupinfo_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupinfo',
            name='ranking',
            field=models.IntegerField(db_column='RANKING', null=True, verbose_name='랭킹'),
        ),
    ]
