# Generated by Django 2.2.10 on 2020-04-03 00:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onepanman_api', '0018_auto_20200401_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user',
            field=models.OneToOneField(db_column='USER', on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='userInfo', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='유저'),
        ),
    ]
