# Generated by Django 2.2.10 on 2020-04-07 02:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('onepanman_api', '0019_auto_20200403_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupinfo',
            name='leader',
            field=models.ForeignKey(db_column='LEADER', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='그룹장'),
        ),
    ]
