# Generated by Django 2.2.10 on 2020-04-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onepanman_api', '0022_auto_20200418_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='challenger_name',
            field=models.CharField(db_column='CHALLENGER_NAME', default='unknown', max_length=50, verbose_name='challenger_name'),
        ),
        migrations.AddField(
            model_name='game',
            name='opposite_name',
            field=models.CharField(db_column='OPPOSITE_NAME', default='unknown', max_length=50, verbose_name='opposite_name'),
        ),
    ]
