# Generated by Django 2.2.10 on 2020-04-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onepanman_api', '0023_auto_20200420_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='challenger_score_flu',
            field=models.IntegerField(db_column='CHALLENGER_SCORE_FLU', default=20, verbose_name='challenger_score_flu'),
        ),
        migrations.AddField(
            model_name='game',
            name='opposite_score_flu',
            field=models.IntegerField(db_column='OPPOSITE_SCORE_FLU', default=20, verbose_name='opposite_score_flu'),
        ),
    ]
