# Generated by Django 2.2.10 on 2020-04-23 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onepanman_api', '0025_auto_20200422_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='challenger_score_flu',
            field=models.IntegerField(db_column='CHALLENGER_SCORE_FLU', default=0, verbose_name='challenger_score_flu'),
        ),
        migrations.AlterField(
            model_name='game',
            name='opposite_score_flu',
            field=models.IntegerField(db_column='OPPOSITE_SCORE_FLU', default=0, verbose_name='opposite_score_flu'),
        ),
    ]
