# Generated by Django 2.2.10 on 2020-05-02 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onepanman_api', '0026_auto_20200423_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='profileImage',
            field=models.ImageField(db_column='PROFILEIMAGE', default='media/default.jpg', upload_to='', verbose_name='프로필 사진'),
        ),
    ]
