# Generated by Django 2.2.10 on 2020-05-02 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onepanman_api', '0027_auto_20200502_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='description',
            field=models.FileField(db_column='DESCRIPTION', default='media/default.jpg', upload_to='', verbose_name='문제PDF'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='icon',
            field=models.ImageField(db_column='ICON', default='media/default.jpg', upload_to='', verbose_name='문제아이콘'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='thumbnail',
            field=models.ImageField(db_column='THUMBNAIL', default='media/default.jpg', upload_to='', verbose_name='문제썸네일'),
        ),
    ]
