# Generated by Django 2.2.10 on 2020-05-26 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onepanman_api', '0028_auto_20200502_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='level',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='popularity',
        ),
    ]
