# Generated by Django 2.2.10 on 2020-05-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onepanman_api', '0029_auto_20200526_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='board_info',
            field=models.TextField(db_column='BOARD_INFO', default='[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]', verbose_name='시작 보드 정보'),
        ),
    ]
