# Generated by Django 2.2.10 on 2020-06-01 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onepanman_api', '0030_auto_20200526_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='type',
            field=models.CharField(db_column='TYPE', default='normal', max_length=50, verbose_name='game type'),
        ),
    ]
