MISS_POSITION = 'miss position'
OUT_OF_RANGE = 'out of range'
TIME_OVER = 'time over'
OUTPUT_ERROR = 'output error'
RUNTIME_ERROR = 'runtime error'
TYPE_ERROR = 'not correct type'
GAME_ERROR = 'game error'
SERVER_ERROR = 'server error'
